name: Release (Beta / Stable)

on: 
  release:
    types: [created]
    
jobs:
  publish:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - release-name: anycpu
          - release-name: x64-standalone
            release: -r win-x64
            pub-folder: win-x64/
            self-contained: --self-contained true
          - release-name: x86-standalone
            release: -r win-x86
            pub-folder: win-x86/
            self-contained: --self-contained true
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.300
    - name: Build and publish
      run: dotnet publish ${{ matrix.release }} -c Release ${{ matrix.self-contained }}
    - name: Zip published files
      run: compress-archive -path ./bin/net8.0-windows/${{ matrix.pub-folder }}publish/* -destinationpath ./bin/net8.0-windows/wfn-${{ matrix.release-name }}.zip
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./bin/net8.0-windows/wfn-${{ matrix.release-name }}.zip
          asset_name: wfn-${{ steps.get_release.outputs.tag_name }}-${{ matrix.release-name }}.zip 
          asset_content_type: application/zip 
      